FROM python:3.12-slim-bookworm

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1

WORKDIR /app

COPY pyproject.toml README.md alembic.ini ./
COPY app ./app
COPY migrations ./migrations
COPY scripts/start_api.sh /start_api.sh

RUN pip install --no-cache-dir . \
    && chmod +x /start_api.sh

EXPOSE 8000
CMD ["/start_api.sh"]
