"""Canonical machine and engineering evidence model.

Revision ID: 0009_engineering
Revises: 0008_embedding_dim
Create Date: 2026-09-01 17:36:41.949768
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# Native enum types outlive the tables that use them, so downgrade has to drop
# them explicitly - otherwise a later upgrade fails with "type already exists".
ENUM_TYPES = (
    "package_status",
    "identity_status",
    "assignment_state",
    "entity_kind",
    "engineering_relation_kind",
    "evidence_locator_kind",
    "evidence_subject_kind",
    "plc_dialect",
    "plc_reference_kind",
    "conflict_kind",
    "conflict_status",
    "behavior_claim_kind",
)

revision: str = "0009_engineering"
down_revision: str | None = "0008_embedding_dim"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "machine_packages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum("draft", "needs_review", "ready", name="package_status"),
            server_default="draft",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_machine_packages_tenant_id_id"),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_machine_packages_tenant_slug"),
    )
    op.create_index("ix_machine_packages_tenant", "machine_packages", ["tenant_id"], unique=False)
    op.create_table(
        "derived_behavior_claims",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column(
            "claim_kind",
            sa.Enum("sequence", "interlock", "alarm_chain", "other", name="behavior_claim_kind"),
            nullable=False,
        ),
        sa.Column(
            "identity_status",
            sa.Enum("unresolved", "resolved", "conflicted", name="identity_status"),
            server_default="unresolved",
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("method_version", sa.String(length=64), nullable=False),
        sa.Column(
            "dependency_path",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(dependency_path) = 'array'", name="ck_behavior_claims_dependency_array"
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_behavior_claims_confidence"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "package_id"],
            ["machine_packages.tenant_id", "machine_packages.id"],
            name="fk_behavior_claims_tenant_package",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_behavior_claims_tenant_id_id"),
    )
    op.create_index(
        "ix_behavior_claims_tenant_package",
        "derived_behavior_claims",
        ["tenant_id", "package_id"],
        unique=False,
    )
    op.create_table(
        "engineering_conflicts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column(
            "conflict_kind",
            sa.Enum(
                "identity", "connectivity", "mapping", "revision", "other", name="conflict_kind"
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("open", "resolved", "accepted_ambiguity", name="conflict_status"),
            server_default="open",
            nullable=False,
        ),
        sa.Column("left_subject_kind", sa.String(length=64), nullable=False),
        sa.Column("left_subject_id", sa.UUID(), nullable=False),
        sa.Column("right_subject_kind", sa.String(length=64), nullable=False),
        sa.Column("right_subject_id", sa.UUID(), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("method_version", sa.String(length=64), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "package_id"],
            ["machine_packages.tenant_id", "machine_packages.id"],
            name="fk_engineering_conflicts_tenant_package",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_engineering_conflicts_tenant_id_id"),
    )
    op.create_index(
        "ix_engineering_conflicts_tenant_package",
        "engineering_conflicts",
        ["tenant_id", "package_id"],
        unique=False,
    )
    op.create_table(
        "human_overrides",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column(
            "subject_kind",
            sa.Enum(
                "package_assignment",
                "entity",
                "entity_candidate",
                "relation",
                "relation_candidate",
                "plc_program",
                "plc_block",
                "plc_variable",
                "plc_reference",
                "conflict",
                "unsupported_construct",
                "behavior_claim",
                "human_override",
                name="evidence_subject_kind",
            ),
            nullable=False,
        ),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column(
            "previous_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "new_payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "package_id"],
            ["machine_packages.tenant_id", "machine_packages.id"],
            name="fk_human_overrides_tenant_package",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_human_overrides_tenant_id_id"),
    )
    op.create_index(
        "ix_human_overrides_tenant_subject",
        "human_overrides",
        ["tenant_id", "subject_kind", "subject_id"],
        unique=False,
    )
    op.create_table(
        "machines",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=True),
        sa.Column("revision", sa.String(length=64), nullable=True),
        sa.Column(
            "identity_status",
            sa.Enum("unresolved", "resolved", "conflicted", name="identity_status"),
            server_default="unresolved",
            nullable=False,
        ),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "package_id"],
            ["machine_packages.tenant_id", "machine_packages.id"],
            name="fk_machines_tenant_package",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_machines_tenant_id_id"),
    )
    op.create_index(
        "ix_machines_tenant_package", "machines", ["tenant_id", "package_id"], unique=False
    )
    op.create_index(
        "uq_machines_package_code",
        "machines",
        ["tenant_id", "package_id", "code"],
        unique=True,
        postgresql_where=sa.text("code IS NOT NULL"),
    )
    op.create_table(
        "package_documents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("relative_path", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "document_id"],
            ["documents.tenant_id", "documents.id"],
            name="fk_package_documents_tenant_document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "package_id"],
            ["machine_packages.tenant_id", "machine_packages.id"],
            name="fk_package_documents_tenant_package",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_package_documents_tenant_id_id"),
        sa.UniqueConstraint(
            "tenant_id", "package_id", "document_id", name="uq_package_documents_membership"
        ),
    )
    op.create_index(
        "ix_package_documents_tenant_document",
        "package_documents",
        ["tenant_id", "document_id"],
        unique=False,
    )
    op.create_table(
        "unsupported_constructs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("construct_code", sa.String(length=128), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("method_version", sa.String(length=64), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "document_id"],
            ["documents.tenant_id", "documents.id"],
            name="fk_unsupported_constructs_tenant_document",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "package_id"],
            ["machine_packages.tenant_id", "machine_packages.id"],
            name="fk_unsupported_constructs_tenant_package",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_unsupported_constructs_tenant_id_id"),
    )
    op.create_index(
        "ix_unsupported_constructs_tenant_package",
        "unsupported_constructs",
        ["tenant_id", "package_id"],
        unique=False,
    )
    op.create_table(
        "assemblies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("machine_id", sa.UUID(), nullable=False),
        sa.Column("parent_assembly_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id <> parent_assembly_id", name="ck_assemblies_no_self_parent"),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machines.tenant_id", "machines.id"],
            name="fk_assemblies_tenant_machine",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "package_id"],
            ["machine_packages.tenant_id", "machine_packages.id"],
            name="fk_assemblies_tenant_package",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "parent_assembly_id"],
            ["assemblies.tenant_id", "assemblies.id"],
            name="fk_assemblies_tenant_parent",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_assemblies_tenant_id_id"),
    )
    op.create_index(
        "ix_assemblies_tenant_machine", "assemblies", ["tenant_id", "machine_id"], unique=False
    )
    op.create_index(
        "uq_assemblies_package_code",
        "assemblies",
        ["tenant_id", "package_id", "code"],
        unique=True,
        postgresql_where=sa.text("code IS NOT NULL"),
    )
    op.create_table(
        "evidence_references",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column(
            "locator_kind",
            sa.Enum(
                "chunk",
                "page",
                "sheet_cell",
                "image_region",
                "xml_path",
                "line_range",
                "native_id",
                name="evidence_locator_kind",
            ),
            nullable=False,
        ),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("source_id", sa.String(length=128), nullable=True),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("sheet_name", sa.String(length=255), nullable=True),
        sa.Column("cell_range", sa.String(length=64), nullable=True),
        sa.Column("xml_path", sa.Text(), nullable=True),
        sa.Column("line_start", sa.Integer(), nullable=True),
        sa.Column("line_end", sa.Integer(), nullable=True),
        sa.Column("native_object_id", sa.String(length=255), nullable=True),
        sa.Column(
            "region",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "line_end IS NULL OR line_start IS NULL OR line_end >= line_start",
            name="ck_evidence_references_line_range",
        ),
        sa.CheckConstraint(
            "line_start IS NULL OR line_start >= 0", name="ck_evidence_references_line_start"
        ),
        sa.CheckConstraint(
            "page_number IS NULL OR page_number > 0", name="ck_evidence_references_page_positive"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "document_id"],
            ["documents.tenant_id", "documents.id"],
            name="fk_evidence_references_tenant_document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_id"],
            ["chunks.tenant_id", "chunks.source_id"],
            name="fk_evidence_references_tenant_source_id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_evidence_references_tenant_id_id"),
    )
    op.create_index(
        "ix_evidence_references_tenant_document",
        "evidence_references",
        ["tenant_id", "document_id"],
        unique=False,
    )
    op.create_table(
        "plc_programs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("machine_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column(
            "dialect",
            sa.Enum("tia_s7", "s5", "plcopen", "unknown", name="plc_dialect"),
            server_default="unknown",
            nullable=False,
        ),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machines.tenant_id", "machines.id"],
            name="fk_plc_programs_tenant_machine",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "package_id"],
            ["machine_packages.tenant_id", "machine_packages.id"],
            name="fk_plc_programs_tenant_package",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_plc_programs_tenant_id_id"),
    )
    op.create_index(
        "ix_plc_programs_tenant_package", "plc_programs", ["tenant_id", "package_id"], unique=False
    )
    op.create_table(
        "engineering_entities",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("machine_id", sa.UUID(), nullable=True),
        sa.Column("assembly_id", sa.UUID(), nullable=True),
        sa.Column(
            "entity_kind",
            sa.Enum(
                "component",
                "signal",
                "port",
                "terminal",
                "cable",
                "connection",
                "other",
                name="entity_kind",
            ),
            nullable=False,
        ),
        sa.Column("canonical_name", sa.String(length=255), nullable=False),
        sa.Column(
            "aliases",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "identity_status",
            sa.Enum("unresolved", "resolved", "conflicted", name="identity_status"),
            server_default="unresolved",
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("method_version", sa.String(length=64), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_engineering_entities_confidence"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "assembly_id"],
            ["assemblies.tenant_id", "assemblies.id"],
            name="fk_engineering_entities_tenant_assembly",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machines.tenant_id", "machines.id"],
            name="fk_engineering_entities_tenant_machine",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "package_id"],
            ["machine_packages.tenant_id", "machine_packages.id"],
            name="fk_engineering_entities_tenant_package",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_engineering_entities_tenant_id_id"),
    )
    op.create_index(
        "ix_engineering_entities_tenant_kind",
        "engineering_entities",
        ["tenant_id", "entity_kind"],
        unique=False,
    )
    op.create_index(
        "ix_engineering_entities_tenant_package",
        "engineering_entities",
        ["tenant_id", "package_id"],
        unique=False,
    )
    op.create_table(
        "evidence_bindings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column(
            "subject_kind",
            sa.Enum(
                "package_assignment",
                "entity",
                "entity_candidate",
                "relation",
                "relation_candidate",
                "plc_program",
                "plc_block",
                "plc_variable",
                "plc_reference",
                "conflict",
                "unsupported_construct",
                "behavior_claim",
                "human_override",
                name="evidence_subject_kind",
            ),
            nullable=False,
        ),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "evidence_id"],
            ["evidence_references.tenant_id", "evidence_references.id"],
            name="fk_evidence_bindings_tenant_evidence",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id",
            "evidence_id",
            "subject_kind",
            "subject_id",
            name="uq_evidence_bindings_link",
        ),
    )
    op.create_index(
        "ix_evidence_bindings_tenant_subject",
        "evidence_bindings",
        ["tenant_id", "subject_kind", "subject_id"],
        unique=False,
    )
    op.create_table(
        "package_assignments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=False),
        sa.Column("machine_id", sa.UUID(), nullable=True),
        sa.Column("assembly_id", sa.UUID(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "proposed",
                "accepted",
                "needs_review",
                "superseded",
                "rejected",
                name="assignment_state",
            ),
            server_default="proposed",
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("method_version", sa.String(length=64), nullable=False),
        sa.Column(
            "reason",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_package_assignments_confidence"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "assembly_id"],
            ["assemblies.tenant_id", "assemblies.id"],
            name="fk_package_assignments_tenant_assembly",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "document_id"],
            ["documents.tenant_id", "documents.id"],
            name="fk_package_assignments_tenant_document",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "machine_id"],
            ["machines.tenant_id", "machines.id"],
            name="fk_package_assignments_tenant_machine",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "package_id"],
            ["machine_packages.tenant_id", "machine_packages.id"],
            name="fk_package_assignments_tenant_package",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_package_assignments_tenant_id_id"),
    )
    op.create_index(
        "ix_package_assignments_tenant_document",
        "package_assignments",
        ["tenant_id", "document_id"],
        unique=False,
    )
    op.create_table(
        "plc_blocks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("block_type", sa.String(length=32), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=True),
        sa.Column("original_identifier", sa.String(length=255), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "program_id"],
            ["plc_programs.tenant_id", "plc_programs.id"],
            name="fk_plc_blocks_tenant_program",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("program_id", "name", name="uq_plc_blocks_program_name"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_plc_blocks_tenant_id_id"),
    )
    op.create_index(
        "ix_plc_blocks_tenant_program", "plc_blocks", ["tenant_id", "program_id"], unique=False
    )
    op.create_table(
        "engineering_entity_candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("canonical_entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "entity_kind",
            sa.Enum(
                "component",
                "signal",
                "port",
                "terminal",
                "cable",
                "connection",
                "other",
                name="entity_kind",
            ),
            nullable=False,
        ),
        sa.Column("proposed_name", sa.String(length=255), nullable=False),
        sa.Column(
            "aliases",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "identity_status",
            sa.Enum("unresolved", "resolved", "conflicted", name="identity_status"),
            server_default="unresolved",
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("method_version", sa.String(length=64), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_entity_candidates_confidence"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "canonical_entity_id"],
            ["engineering_entities.tenant_id", "engineering_entities.id"],
            name="fk_entity_candidates_tenant_canonical",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "package_id"],
            ["machine_packages.tenant_id", "machine_packages.id"],
            name="fk_entity_candidates_tenant_package",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_entity_candidates_tenant_id_id"),
    )
    op.create_index(
        "ix_entity_candidates_tenant_package",
        "engineering_entity_candidates",
        ["tenant_id", "package_id"],
        unique=False,
    )
    op.create_table(
        "engineering_relations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column(
            "relation_kind",
            sa.Enum(
                "connected_to",
                "maps_to",
                "contains",
                "calls",
                "reads",
                "writes",
                "related",
                name="engineering_relation_kind",
            ),
            nullable=False,
        ),
        sa.Column("source_entity_id", sa.UUID(), nullable=False),
        sa.Column("target_entity_id", sa.UUID(), nullable=False),
        sa.Column(
            "identity_status",
            sa.Enum("unresolved", "resolved", "conflicted", name="identity_status"),
            server_default="unresolved",
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("method_version", sa.String(length=64), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_engineering_relations_confidence"
        ),
        sa.CheckConstraint(
            "source_entity_id <> target_entity_id", name="ck_engineering_relations_no_self_edge"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "package_id"],
            ["machine_packages.tenant_id", "machine_packages.id"],
            name="fk_engineering_relations_tenant_package",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_entity_id"],
            ["engineering_entities.tenant_id", "engineering_entities.id"],
            name="fk_engineering_relations_tenant_source",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "target_entity_id"],
            ["engineering_entities.tenant_id", "engineering_entities.id"],
            name="fk_engineering_relations_tenant_target",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_engineering_relations_tenant_id_id"),
        sa.UniqueConstraint(
            "tenant_id",
            "package_id",
            "source_entity_id",
            "target_entity_id",
            "relation_kind",
            name="uq_engineering_relations_edge",
        ),
    )
    op.create_index(
        "ix_engineering_relations_tenant_package",
        "engineering_relations",
        ["tenant_id", "package_id"],
        unique=False,
    )
    op.create_table(
        "plc_variables",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("program_id", sa.UUID(), nullable=False),
        sa.Column("block_id", sa.UUID(), nullable=True),
        sa.Column("entity_id", sa.UUID(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("data_type", sa.String(length=128), nullable=True),
        sa.Column("address", sa.String(length=128), nullable=True),
        sa.Column("io_direction", sa.String(length=32), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "block_id"],
            ["plc_blocks.tenant_id", "plc_blocks.id"],
            name="fk_plc_variables_tenant_block",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "entity_id"],
            ["engineering_entities.tenant_id", "engineering_entities.id"],
            name="fk_plc_variables_tenant_entity",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "program_id"],
            ["plc_programs.tenant_id", "plc_programs.id"],
            name="fk_plc_variables_tenant_program",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_plc_variables_tenant_id_id"),
    )
    op.create_index(
        "ix_plc_variables_tenant_entity", "plc_variables", ["tenant_id", "entity_id"], unique=False
    )
    op.create_index(
        "ix_plc_variables_tenant_program",
        "plc_variables",
        ["tenant_id", "program_id"],
        unique=False,
    )
    op.create_table(
        "engineering_relation_candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("package_id", sa.UUID(), nullable=False),
        sa.Column("canonical_relation_id", sa.UUID(), nullable=True),
        sa.Column(
            "relation_kind",
            sa.Enum(
                "connected_to",
                "maps_to",
                "contains",
                "calls",
                "reads",
                "writes",
                "related",
                name="engineering_relation_kind",
            ),
            nullable=False,
        ),
        sa.Column("source_entity_id", sa.UUID(), nullable=True),
        sa.Column("target_entity_id", sa.UUID(), nullable=True),
        sa.Column(
            "identity_status",
            sa.Enum("unresolved", "resolved", "conflicted", name="identity_status"),
            server_default="unresolved",
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("method_version", sa.String(length=64), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 1", name="ck_relation_candidates_confidence"
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "canonical_relation_id"],
            ["engineering_relations.tenant_id", "engineering_relations.id"],
            name="fk_relation_candidates_tenant_canonical",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "package_id"],
            ["machine_packages.tenant_id", "machine_packages.id"],
            name="fk_relation_candidates_tenant_package",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "source_entity_id"],
            ["engineering_entities.tenant_id", "engineering_entities.id"],
            name="fk_relation_candidates_tenant_source",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "target_entity_id"],
            ["engineering_entities.tenant_id", "engineering_entities.id"],
            name="fk_relation_candidates_tenant_target",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_relation_candidates_tenant_id_id"),
    )
    op.create_index(
        "ix_relation_candidates_tenant_package",
        "engineering_relation_candidates",
        ["tenant_id", "package_id"],
        unique=False,
    )
    op.create_table(
        "plc_references",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("block_id", sa.UUID(), nullable=False),
        sa.Column("variable_id", sa.UUID(), nullable=True),
        sa.Column(
            "reference_kind",
            sa.Enum("read", "write", "call", "condition", name="plc_reference_kind"),
            nullable=False,
        ),
        sa.Column("network_ordinal", sa.Integer(), nullable=True),
        sa.Column("original_construct", sa.String(length=64), nullable=True),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "network_ordinal IS NULL OR network_ordinal >= 0",
            name="ck_plc_references_network_ordinal",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "block_id"],
            ["plc_blocks.tenant_id", "plc_blocks.id"],
            name="fk_plc_references_tenant_block",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "variable_id"],
            ["plc_variables.tenant_id", "plc_variables.id"],
            name="fk_plc_references_tenant_variable",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "id", name="uq_plc_references_tenant_id_id"),
    )
    op.create_index(
        "ix_plc_references_tenant_block", "plc_references", ["tenant_id", "block_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_plc_references_tenant_block", table_name="plc_references")
    op.drop_table("plc_references")
    op.drop_index(
        "ix_relation_candidates_tenant_package", table_name="engineering_relation_candidates"
    )
    op.drop_table("engineering_relation_candidates")
    op.drop_index("ix_plc_variables_tenant_program", table_name="plc_variables")
    op.drop_index("ix_plc_variables_tenant_entity", table_name="plc_variables")
    op.drop_table("plc_variables")
    op.drop_index("ix_engineering_relations_tenant_package", table_name="engineering_relations")
    op.drop_table("engineering_relations")
    op.drop_index("ix_entity_candidates_tenant_package", table_name="engineering_entity_candidates")
    op.drop_table("engineering_entity_candidates")
    op.drop_index("ix_plc_blocks_tenant_program", table_name="plc_blocks")
    op.drop_table("plc_blocks")
    op.drop_index("ix_package_assignments_tenant_document", table_name="package_assignments")
    op.drop_table("package_assignments")
    op.drop_index("ix_evidence_bindings_tenant_subject", table_name="evidence_bindings")
    op.drop_table("evidence_bindings")
    op.drop_index("ix_engineering_entities_tenant_package", table_name="engineering_entities")
    op.drop_index("ix_engineering_entities_tenant_kind", table_name="engineering_entities")
    op.drop_table("engineering_entities")
    op.drop_index("ix_plc_programs_tenant_package", table_name="plc_programs")
    op.drop_table("plc_programs")
    op.drop_index("ix_evidence_references_tenant_document", table_name="evidence_references")
    op.drop_table("evidence_references")
    op.drop_index(
        "uq_assemblies_package_code",
        table_name="assemblies",
        postgresql_where=sa.text("code IS NOT NULL"),
    )
    op.drop_index("ix_assemblies_tenant_machine", table_name="assemblies")
    op.drop_table("assemblies")
    op.drop_index("ix_unsupported_constructs_tenant_package", table_name="unsupported_constructs")
    op.drop_table("unsupported_constructs")
    op.drop_index("ix_package_documents_tenant_document", table_name="package_documents")
    op.drop_table("package_documents")
    op.drop_index(
        "uq_machines_package_code",
        table_name="machines",
        postgresql_where=sa.text("code IS NOT NULL"),
    )
    op.drop_index("ix_machines_tenant_package", table_name="machines")
    op.drop_table("machines")
    op.drop_index("ix_human_overrides_tenant_subject", table_name="human_overrides")
    op.drop_table("human_overrides")
    op.drop_index("ix_engineering_conflicts_tenant_package", table_name="engineering_conflicts")
    op.drop_table("engineering_conflicts")
    op.drop_index("ix_behavior_claims_tenant_package", table_name="derived_behavior_claims")
    op.drop_table("derived_behavior_claims")
    op.drop_index("ix_machine_packages_tenant", table_name="machine_packages")
    op.drop_table("machine_packages")
    bind = op.get_bind()
    for name in ENUM_TYPES:
        postgresql.ENUM(name=name, create_type=False).drop(bind, checkfirst=True)
    # ### end Alembic commands ###
